### PR TITLE
support VRT file input for sequential --bbox

### PR DESCRIPTION
**Pull request by yunjunz**
This PR adds support of VRT file for `sequential.py --bbox` option, besides the existing input style.

It also fixes some typo and broken links in the document.

### CODE REVIEW

**Comment by piyushrpt** [comment]
I see this is for the case when a cropped VRT has already been setup, correct? 
That way, you don't have to remember the box limits all the time for every command. 
Am I interpreting this correctly?

**Comment by yunjunz** [comment]
Yes, exactly @piyushrpt.

**Comment by hfattahi** [comment]
I think, we have tried to minimize dependencies (at least for core fringe modules). Isce is a significant dependency to add just to get the xml files which are not needed anywhere in fringe. I suggest to eleminate gdal2isce_xml.py commands. A user can always run that later if needed.

**Comment by yunjunz** [comment]
Thank you @hfattahi for the suggestion, I did not realize that `isce` is not a dependency here. Besides the gdal2isce_xml.py call, I will also comment out the `isceobj.Util.ImageUtil.ImageLib` call here introduced in #14 then, otherwise, the script will return error if no XML file exists.

**Comment by dbekaert** [comment]
Perhaps we should then also remove ISCE2 from the conda suggested dependency under install guidelines?

 It is not mentioned in the prerequisite but included it explicitly says that isce2 should be installed in the macOS and conda example. Same applies for the PATH exports.  For now i had it included in the cricleCI build i am setting up, but i can remove it again.

see here: https://github.com/isce-framework/fringe/blob/master/docs/install.md

**Pull request merged**
